-- ============================================================
-- ONTYX ERP — Complete Supabase Schema
-- Generated by NEXUS · 2026-02-14
-- Canadian-first, multi-currency, production-ready
-- ============================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- ENUMS
-- ============================================================

CREATE TYPE contact_type AS ENUM ('customer', 'vendor', 'both');
CREATE TYPE contact_category AS ENUM ('individual', 'company');
CREATE TYPE address_type AS ENUM ('billing', 'shipping', 'other');

CREATE TYPE invoice_status AS ENUM ('draft', 'sent', 'viewed', 'paid', 'partial', 'overdue', 'cancelled');
CREATE TYPE bill_status AS ENUM ('draft', 'pending', 'approved', 'paid', 'partial', 'overdue', 'cancelled');
CREATE TYPE payment_method AS ENUM ('cash', 'cheque', 'bank_transfer', 'credit_card', 'eft', 'interac', 'other');

CREATE TYPE bank_transaction_type AS ENUM ('income', 'expense', 'transfer');
CREATE TYPE reconciliation_status AS ENUM ('unreconciled', 'matched', 'reconciled');

CREATE TYPE account_type AS ENUM ('asset', 'liability', 'equity', 'revenue', 'expense');

CREATE TYPE product_status AS ENUM ('active', 'inactive', 'discontinued', 'out_of_stock');
CREATE TYPE stock_movement_type AS ENUM ('in', 'out', 'adjustment', 'transfer');

CREATE TYPE warehouse_status AS ENUM ('active', 'inactive', 'maintenance');
CREATE TYPE zone_type AS ENUM ('storage', 'picking', 'receiving', 'shipping', 'staging');
CREATE TYPE transfer_status AS ENUM ('pending', 'in_transit', 'completed', 'cancelled');

CREATE TYPE sales_order_status AS ENUM ('draft', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'returned');
CREATE TYPE quote_status AS ENUM ('draft', 'sent', 'accepted', 'rejected', 'expired');
CREATE TYPE payment_status AS ENUM ('pending', 'partial', 'paid', 'refunded');
CREATE TYPE shipping_method AS ENUM ('standard', 'express', 'overnight', 'pickup');

CREATE TYPE purchase_order_status AS ENUM ('draft', 'sent', 'confirmed', 'partial', 'received', 'cancelled');
CREATE TYPE receiving_status AS ENUM ('pending', 'partial', 'complete');
CREATE TYPE goods_condition AS ENUM ('good', 'damaged', 'rejected');

CREATE TYPE work_order_status AS ENUM ('draft', 'planned', 'in_progress', 'on_hold', 'completed', 'cancelled');
CREATE TYPE work_order_priority AS ENUM ('low', 'medium', 'high', 'urgent');
CREATE TYPE operation_status AS ENUM ('pending', 'in_progress', 'completed');
CREATE TYPE bom_status AS ENUM ('draft', 'active', 'obsolete');
CREATE TYPE qc_status AS ENUM ('pending', 'passed', 'failed', 'needs_review');
CREATE TYPE qc_result AS ENUM ('pass', 'fail', 'pending');

CREATE TYPE lead_status AS ENUM ('new', 'contacted', 'qualified', 'unqualified');
CREATE TYPE deal_stage AS ENUM ('lead', 'qualified', 'proposal', 'negotiation', 'won', 'lost');
CREATE TYPE activity_type AS ENUM ('call', 'email', 'meeting', 'task', 'note');
CREATE TYPE priority_level AS ENUM ('low', 'medium', 'high', 'urgent');

CREATE TYPE employment_type AS ENUM ('full-time', 'part-time', 'contract', 'intern');
CREATE TYPE employment_status AS ENUM ('active', 'on-leave', 'terminated', 'resigned');

CREATE TYPE payroll_status AS ENUM ('draft', 'pending', 'processing', 'completed', 'cancelled');
CREATE TYPE pay_period AS ENUM ('weekly', 'bi-weekly', 'semi-monthly', 'monthly');
CREATE TYPE payslip_status AS ENUM ('draft', 'approved', 'paid', 'cancelled');
CREATE TYPE earning_type AS ENUM ('salary', 'bonus', 'overtime', 'commission', 'allowance', 'other');
CREATE TYPE deduction_type AS ENUM ('tax', 'insurance', 'retirement', 'garnishment', 'cpp', 'ei', 'other');

CREATE TYPE project_status AS ENUM ('planning', 'active', 'on_hold', 'completed', 'cancelled');
CREATE TYPE project_priority AS ENUM ('low', 'medium', 'high', 'critical');
CREATE TYPE task_status AS ENUM ('todo', 'in_progress', 'review', 'completed', 'blocked');
CREATE TYPE milestone_status AS ENUM ('pending', 'achieved', 'missed');
CREATE TYPE time_entry_status AS ENUM ('draft', 'submitted', 'approved', 'rejected');

CREATE TYPE notification_type AS ENUM ('info', 'warning', 'error', 'success');
CREATE TYPE notification_channel AS ENUM ('in_app', 'email', 'sms');

-- ============================================================
-- 1. SETTINGS & CONFIGURATION
-- ============================================================

CREATE TABLE currencies (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  code VARCHAR(3) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  symbol VARCHAR(10) NOT NULL,
  exchange_rate DECIMAL(18,6) NOT NULL DEFAULT 1.000000,
  is_base BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  decimal_places INT NOT NULL DEFAULT 2,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE company_settings (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(255) NOT NULL,
  legal_name VARCHAR(255),
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(50),
  website VARCHAR(255),
  address_line1 VARCHAR(255),
  address_line2 VARCHAR(255),
  city VARCHAR(100),
  province VARCHAR(100),
  postal_code VARCHAR(20),
  country VARCHAR(100) DEFAULT 'Canada',
  tax_id VARCHAR(50),                    -- GST/HST number
  registration_number VARCHAR(50),       -- Business Number
  logo_url TEXT,
  favicon_url TEXT,
  base_currency_id UUID REFERENCES currencies(id),
  timezone VARCHAR(50) DEFAULT 'America/Toronto',
  fiscal_year_start VARCHAR(20) DEFAULT 'January',
  industry VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE tax_rates (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(100) NOT NULL,
  code VARCHAR(20) NOT NULL UNIQUE,
  rate DECIMAL(6,4) NOT NULL,
  description TEXT,
  is_compound BOOLEAN DEFAULT FALSE,
  is_active BOOLEAN DEFAULT TRUE,
  region VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE fiscal_years (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(100) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  is_closed BOOLEAN DEFAULT FALSE,
  closed_at TIMESTAMPTZ,
  closed_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE system_settings (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  invoice_prefix VARCHAR(10) DEFAULT 'INV',
  invoice_next_number INT DEFAULT 1,
  bill_prefix VARCHAR(10) DEFAULT 'BILL',
  bill_next_number INT DEFAULT 1,
  quote_prefix VARCHAR(10) DEFAULT 'QT',
  quote_next_number INT DEFAULT 1,
  sales_order_prefix VARCHAR(10) DEFAULT 'SO',
  sales_order_next_number INT DEFAULT 1,
  purchase_order_prefix VARCHAR(10) DEFAULT 'PO',
  purchase_order_next_number INT DEFAULT 1,
  work_order_prefix VARCHAR(10) DEFAULT 'WO',
  work_order_next_number INT DEFAULT 1,
  project_code_prefix VARCHAR(10) DEFAULT 'PRJ',
  project_next_number INT DEFAULT 1,
  default_payment_terms INT DEFAULT 30,
  default_tax_rate_id UUID REFERENCES tax_rates(id),
  auto_backup BOOLEAN DEFAULT TRUE,
  backup_frequency VARCHAR(20) DEFAULT 'daily',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 2. CONTACTS (Customers, Vendors, Leads)
-- ============================================================

CREATE TABLE contacts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  type contact_type NOT NULL DEFAULT 'customer',
  category contact_category NOT NULL DEFAULT 'company',
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  phone VARCHAR(50),
  company VARCHAR(255),
  job_title VARCHAR(100),
  avatar_url TEXT,
  website VARCHAR(255),
  tax_id VARCHAR(50),
  notes TEXT,
  tags TEXT[] DEFAULT '{}',
  balance DECIMAL(18,2) DEFAULT 0,
  total_revenue DECIMAL(18,2) DEFAULT 0,
  total_orders INT DEFAULT 0,
  credit_limit DECIMAL(18,2),
  payment_terms INT DEFAULT 30,
  currency_id UUID REFERENCES currencies(id),
  is_active BOOLEAN DEFAULT TRUE,
  last_contacted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE contact_addresses (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  contact_id UUID NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  type address_type NOT NULL DEFAULT 'billing',
  line1 VARCHAR(255) NOT NULL,
  line2 VARCHAR(255),
  city VARCHAR(100) NOT NULL,
  province VARCHAR(100),
  postal_code VARCHAR(20),
  country VARCHAR(100) DEFAULT 'Canada',
  is_primary BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE contact_activities (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  contact_id UUID NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  type activity_type NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  user_name VARCHAR(255),
  user_id UUID,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 3. ACCOUNTING (Chart of Accounts, Journal Entries)
-- ============================================================

CREATE TABLE chart_of_accounts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  code VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  type account_type NOT NULL,
  parent_id UUID REFERENCES chart_of_accounts(id),
  description TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  is_system BOOLEAN DEFAULT FALSE,
  balance DECIMAL(18,2) DEFAULT 0,
  currency_id UUID REFERENCES currencies(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE journal_entries (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  entry_number VARCHAR(50) NOT NULL UNIQUE,
  date DATE NOT NULL,
  description TEXT NOT NULL,
  reference VARCHAR(100),
  total_debit DECIMAL(18,2) NOT NULL DEFAULT 0,
  total_credit DECIMAL(18,2) NOT NULL DEFAULT 0,
  is_posted BOOLEAN DEFAULT FALSE,
  is_adjusting BOOLEAN DEFAULT FALSE,
  fiscal_year_id UUID REFERENCES fiscal_years(id),
  created_by VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  posted_at TIMESTAMPTZ
);

CREATE TABLE journal_lines (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  journal_entry_id UUID NOT NULL REFERENCES journal_entries(id) ON DELETE CASCADE,
  account_id UUID NOT NULL REFERENCES chart_of_accounts(id),
  description TEXT,
  debit DECIMAL(18,2) NOT NULL DEFAULT 0,
  credit DECIMAL(18,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 4. INVOICES (Accounts Receivable)
-- ============================================================

CREATE TABLE invoices (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  invoice_number VARCHAR(50) NOT NULL UNIQUE,
  customer_id UUID NOT NULL REFERENCES contacts(id),
  status invoice_status NOT NULL DEFAULT 'draft',
  issue_date DATE NOT NULL,
  due_date DATE NOT NULL,
  subtotal DECIMAL(18,2) NOT NULL DEFAULT 0,
  tax_total DECIMAL(18,2) NOT NULL DEFAULT 0,
  discount_total DECIMAL(18,2) NOT NULL DEFAULT 0,
  total DECIMAL(18,2) NOT NULL DEFAULT 0,
  amount_paid DECIMAL(18,2) NOT NULL DEFAULT 0,
  amount_due DECIMAL(18,2) NOT NULL DEFAULT 0,
  currency_id UUID REFERENCES currencies(id),
  exchange_rate DECIMAL(18,6) DEFAULT 1.000000,
  notes TEXT,
  terms TEXT,
  po_reference VARCHAR(100),
  sales_order_id UUID,
  sent_at TIMESTAMPTZ,
  viewed_at TIMESTAMPTZ,
  paid_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE invoice_line_items (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  invoice_id UUID NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  product_id UUID,
  account_id UUID REFERENCES chart_of_accounts(id),
  description TEXT NOT NULL,
  quantity DECIMAL(18,4) NOT NULL DEFAULT 1,
  unit_price DECIMAL(18,4) NOT NULL DEFAULT 0,
  discount_percent DECIMAL(6,2) DEFAULT 0,
  tax_rate_id UUID REFERENCES tax_rates(id),
  tax_amount DECIMAL(18,2) DEFAULT 0,
  amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE invoice_payments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  invoice_id UUID NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  amount DECIMAL(18,2) NOT NULL,
  date DATE NOT NULL,
  method payment_method NOT NULL DEFAULT 'bank_transfer',
  reference VARCHAR(100),
  bank_account_id UUID,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 5. BILLS (Accounts Payable)
-- ============================================================

CREATE TABLE bills (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  bill_number VARCHAR(50) NOT NULL UNIQUE,
  vendor_id UUID NOT NULL REFERENCES contacts(id),
  status bill_status NOT NULL DEFAULT 'draft',
  reference VARCHAR(100),
  issue_date DATE NOT NULL,
  due_date DATE NOT NULL,
  subtotal DECIMAL(18,2) NOT NULL DEFAULT 0,
  tax_total DECIMAL(18,2) NOT NULL DEFAULT 0,
  total DECIMAL(18,2) NOT NULL DEFAULT 0,
  amount_paid DECIMAL(18,2) NOT NULL DEFAULT 0,
  amount_due DECIMAL(18,2) NOT NULL DEFAULT 0,
  currency_id UUID REFERENCES currencies(id),
  exchange_rate DECIMAL(18,6) DEFAULT 1.000000,
  notes TEXT,
  purchase_order_id UUID,
  approved_at TIMESTAMPTZ,
  approved_by VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE bill_line_items (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  bill_id UUID NOT NULL REFERENCES bills(id) ON DELETE CASCADE,
  product_id UUID,
  account_id UUID REFERENCES chart_of_accounts(id),
  description TEXT NOT NULL,
  quantity DECIMAL(18,4) NOT NULL DEFAULT 1,
  unit_price DECIMAL(18,4) NOT NULL DEFAULT 0,
  tax_rate_id UUID REFERENCES tax_rates(id),
  tax_amount DECIMAL(18,2) DEFAULT 0,
  amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE bill_payments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  bill_id UUID NOT NULL REFERENCES bills(id) ON DELETE CASCADE,
  amount DECIMAL(18,2) NOT NULL,
  date DATE NOT NULL,
  method payment_method NOT NULL DEFAULT 'bank_transfer',
  reference VARCHAR(100),
  bank_account_id UUID,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 6. BANKING
-- ============================================================

CREATE TABLE bank_accounts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(255) NOT NULL,
  account_number VARCHAR(50),
  institution_number VARCHAR(10),
  transit_number VARCHAR(10),
  bank_name VARCHAR(255),
  currency_id UUID REFERENCES currencies(id),
  balance DECIMAL(18,2) NOT NULL DEFAULT 0,
  account_id UUID REFERENCES chart_of_accounts(id),
  last_reconciled DATE,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE bank_transactions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  bank_account_id UUID NOT NULL REFERENCES bank_accounts(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  description TEXT NOT NULL,
  reference VARCHAR(100),
  type bank_transaction_type NOT NULL,
  amount DECIMAL(18,2) NOT NULL,
  running_balance DECIMAL(18,2),
  reconciliation_status reconciliation_status DEFAULT 'unreconciled',
  matched_invoice_id UUID REFERENCES invoices(id),
  matched_bill_id UUID REFERENCES bills(id),
  category VARCHAR(100),
  notes TEXT,
  imported_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE reconciliation_rules (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(255) NOT NULL,
  conditions JSONB NOT NULL DEFAULT '[]',
  action JSONB NOT NULL DEFAULT '{}',
  is_active BOOLEAN DEFAULT TRUE,
  match_count INT DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 7. INVENTORY (Products, Categories, Stock)
-- ============================================================

CREATE TABLE product_categories (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  description TEXT,
  parent_id UUID REFERENCES product_categories(id),
  image_url TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE units_of_measure (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(50) NOT NULL,
  abbreviation VARCHAR(10) NOT NULL UNIQUE,
  category VARCHAR(50),
  base_unit_id UUID REFERENCES units_of_measure(id),
  conversion_factor DECIMAL(18,6) DEFAULT 1,
  is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE products (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  sku VARCHAR(50) NOT NULL UNIQUE,
  barcode VARCHAR(50),
  name VARCHAR(255) NOT NULL,
  description TEXT,
  category_id UUID REFERENCES product_categories(id),
  unit_id UUID REFERENCES units_of_measure(id),
  status product_status NOT NULL DEFAULT 'active',
  unit_price DECIMAL(18,4) NOT NULL DEFAULT 0,
  cost_price DECIMAL(18,4) NOT NULL DEFAULT 0,
  tax_rate_id UUID REFERENCES tax_rates(id),
  stock_quantity DECIMAL(18,4) NOT NULL DEFAULT 0,
  reorder_level DECIMAL(18,4) DEFAULT 0,
  reorder_quantity DECIMAL(18,4) DEFAULT 0,
  weight DECIMAL(10,3),
  length DECIMAL(10,2),
  width DECIMAL(10,2),
  height DECIMAL(10,2),
  image_url TEXT,
  tags TEXT[] DEFAULT '{}',
  is_active BOOLEAN DEFAULT TRUE,
  is_service BOOLEAN DEFAULT FALSE,
  revenue_account_id UUID REFERENCES chart_of_accounts(id),
  expense_account_id UUID REFERENCES chart_of_accounts(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE stock_movements (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  product_id UUID NOT NULL REFERENCES products(id),
  warehouse_id UUID,
  type stock_movement_type NOT NULL,
  quantity DECIMAL(18,4) NOT NULL,
  previous_stock DECIMAL(18,4) NOT NULL,
  new_stock DECIMAL(18,4) NOT NULL,
  unit_cost DECIMAL(18,4),
  reference VARCHAR(100),
  notes TEXT,
  created_by VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 8. WAREHOUSES
-- ============================================================

CREATE TABLE warehouses (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  code VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  address VARCHAR(255),
  city VARCHAR(100),
  province VARCHAR(100),
  postal_code VARCHAR(20),
  country VARCHAR(100) DEFAULT 'Canada',
  status warehouse_status NOT NULL DEFAULT 'active',
  capacity INT DEFAULT 0,
  used_capacity INT DEFAULT 0,
  manager_id UUID,
  phone VARCHAR(50),
  email VARCHAR(255),
  is_default BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE warehouse_zones (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  warehouse_id UUID NOT NULL REFERENCES warehouses(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  code VARCHAR(20) NOT NULL,
  type zone_type NOT NULL DEFAULT 'storage',
  capacity INT DEFAULT 0,
  used_capacity INT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE bin_locations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  zone_id UUID NOT NULL REFERENCES warehouse_zones(id) ON DELETE CASCADE,
  code VARCHAR(50) NOT NULL,
  aisle VARCHAR(10),
  rack VARCHAR(10),
  shelf VARCHAR(10),
  bin VARCHAR(10),
  capacity INT DEFAULT 0,
  current_stock INT DEFAULT 0,
  product_id UUID REFERENCES products(id),
  is_available BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE warehouse_stock (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  warehouse_id UUID NOT NULL REFERENCES warehouses(id),
  product_id UUID NOT NULL REFERENCES products(id),
  bin_id UUID REFERENCES bin_locations(id),
  quantity DECIMAL(18,4) NOT NULL DEFAULT 0,
  reserved_quantity DECIMAL(18,4) NOT NULL DEFAULT 0,
  available_quantity DECIMAL(18,4) GENERATED ALWAYS AS (quantity - reserved_quantity) STORED,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(warehouse_id, product_id, bin_id)
);

CREATE TABLE stock_transfers (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  transfer_number VARCHAR(50) NOT NULL UNIQUE,
  from_warehouse_id UUID NOT NULL REFERENCES warehouses(id),
  to_warehouse_id UUID NOT NULL REFERENCES warehouses(id),
  status transfer_status NOT NULL DEFAULT 'pending',
  notes TEXT,
  requested_by VARCHAR(255),
  requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  approved_by VARCHAR(255),
  approved_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE stock_transfer_items (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  transfer_id UUID NOT NULL REFERENCES stock_transfers(id) ON DELETE CASCADE,
  product_id UUID NOT NULL REFERENCES products(id),
  quantity DECIMAL(18,4) NOT NULL,
  from_bin_id UUID REFERENCES bin_locations(id),
  to_bin_id UUID REFERENCES bin_locations(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 9. SALES (Orders, Quotes)
-- ============================================================

CREATE TABLE quotes (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  quote_number VARCHAR(50) NOT NULL UNIQUE,
  customer_id UUID NOT NULL REFERENCES contacts(id),
  status quote_status NOT NULL DEFAULT 'draft',
  subtotal DECIMAL(18,2) NOT NULL DEFAULT 0,
  tax_total DECIMAL(18,2) NOT NULL DEFAULT 0,
  discount_total DECIMAL(18,2) NOT NULL DEFAULT 0,
  total DECIMAL(18,2) NOT NULL DEFAULT 0,
  currency_id UUID REFERENCES currencies(id),
  valid_until DATE,
  notes TEXT,
  terms TEXT,
  converted_order_id UUID,
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE quote_items (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  quote_id UUID NOT NULL REFERENCES quotes(id) ON DELETE CASCADE,
  product_id UUID REFERENCES products(id),
  description TEXT,
  quantity DECIMAL(18,4) NOT NULL DEFAULT 1,
  unit_price DECIMAL(18,4) NOT NULL DEFAULT 0,
  tax_rate_id UUID REFERENCES tax_rates(id),
  discount_percent DECIMAL(6,2) DEFAULT 0,
  amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE sales_orders (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_number VARCHAR(50) NOT NULL UNIQUE,
  customer_id UUID NOT NULL REFERENCES contacts(id),
  quote_id UUID REFERENCES quotes(id),
  invoice_id UUID,
  warehouse_id UUID REFERENCES warehouses(id),
  status sales_order_status NOT NULL DEFAULT 'draft',
  payment_status payment_status NOT NULL DEFAULT 'pending',
  shipping_address JSONB,
  billing_address JSONB,
  subtotal DECIMAL(18,2) NOT NULL DEFAULT 0,
  tax_total DECIMAL(18,2) NOT NULL DEFAULT 0,
  shipping_cost DECIMAL(18,2) NOT NULL DEFAULT 0,
  discount_total DECIMAL(18,2) NOT NULL DEFAULT 0,
  total DECIMAL(18,2) NOT NULL DEFAULT 0,
  amount_paid DECIMAL(18,2) NOT NULL DEFAULT 0,
  amount_due DECIMAL(18,2) NOT NULL DEFAULT 0,
  currency_id UUID REFERENCES currencies(id),
  shipping_method shipping_method DEFAULT 'standard',
  tracking_number VARCHAR(100),
  notes TEXT,
  internal_notes TEXT,
  order_date DATE NOT NULL,
  expected_delivery DATE,
  shipped_at TIMESTAMPTZ,
  delivered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE sales_order_items (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_id UUID NOT NULL REFERENCES sales_orders(id) ON DELETE CASCADE,
  product_id UUID REFERENCES products(id),
  description TEXT,
  quantity DECIMAL(18,4) NOT NULL DEFAULT 1,
  unit_price DECIMAL(18,4) NOT NULL DEFAULT 0,
  tax_rate_id UUID REFERENCES tax_rates(id),
  discount_percent DECIMAL(6,2) DEFAULT 0,
  amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  fulfilled_quantity DECIMAL(18,4) DEFAULT 0,
  backordered_quantity DECIMAL(18,4) DEFAULT 0,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 10. PURCHASES (POs, Goods Receipts)
-- ============================================================

CREATE TABLE purchase_orders (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  po_number VARCHAR(50) NOT NULL UNIQUE,
  vendor_id UUID NOT NULL REFERENCES contacts(id),
  warehouse_id UUID REFERENCES warehouses(id),
  status purchase_order_status NOT NULL DEFAULT 'draft',
  receiving_status receiving_status NOT NULL DEFAULT 'pending',
  subtotal DECIMAL(18,2) NOT NULL DEFAULT 0,
  tax_total DECIMAL(18,2) NOT NULL DEFAULT 0,
  shipping_cost DECIMAL(18,2) NOT NULL DEFAULT 0,
  total DECIMAL(18,2) NOT NULL DEFAULT 0,
  amount_paid DECIMAL(18,2) NOT NULL DEFAULT 0,
  currency_id UUID REFERENCES currencies(id),
  exchange_rate DECIMAL(18,6) DEFAULT 1.000000,
  expected_delivery DATE,
  notes TEXT,
  internal_notes TEXT,
  order_date DATE NOT NULL,
  sent_at TIMESTAMPTZ,
  confirmed_at TIMESTAMPTZ,
  received_at TIMESTAMPTZ,
  created_by VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE purchase_order_items (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  purchase_order_id UUID NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
  product_id UUID REFERENCES products(id),
  description TEXT,
  quantity DECIMAL(18,4) NOT NULL DEFAULT 1,
  received_quantity DECIMAL(18,4) DEFAULT 0,
  unit_cost DECIMAL(18,4) NOT NULL DEFAULT 0,
  tax_rate_id UUID REFERENCES tax_rates(id),
  amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE goods_receipts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  receipt_number VARCHAR(50) NOT NULL UNIQUE,
  purchase_order_id UUID NOT NULL REFERENCES purchase_orders(id),
  vendor_id UUID NOT NULL REFERENCES contacts(id),
  warehouse_id UUID NOT NULL REFERENCES warehouses(id),
  total_quantity DECIMAL(18,4) NOT NULL DEFAULT 0,
  notes TEXT,
  received_by VARCHAR(255),
  received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE goods_receipt_items (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  receipt_id UUID NOT NULL REFERENCES goods_receipts(id) ON DELETE CASCADE,
  product_id UUID NOT NULL REFERENCES products(id),
  ordered_quantity DECIMAL(18,4) NOT NULL,
  received_quantity DECIMAL(18,4) NOT NULL,
  bin_location_id UUID REFERENCES bin_locations(id),
  condition goods_condition DEFAULT 'good',
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 11. MANUFACTURING
-- ============================================================

CREATE TABLE work_centers (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  code VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  capacity_per_hour DECIMAL(10,2) DEFAULT 0,
  cost_per_hour DECIMAL(18,4) DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  current_utilization DECIMAL(5,2) DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE bills_of_materials (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  bom_number VARCHAR(50) NOT NULL UNIQUE,
  product_id UUID NOT NULL REFERENCES products(id),
  version VARCHAR(20) DEFAULT '1.0',
  status bom_status NOT NULL DEFAULT 'draft',
  total_material_cost DECIMAL(18,2) DEFAULT 0,
  labor_cost DECIMAL(18,2) DEFAULT 0,
  overhead_cost DECIMAL(18,2) DEFAULT 0,
  total_production_cost DECIMAL(18,2) DEFAULT 0,
  notes TEXT,
  created_by VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE bom_items (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  bom_id UUID NOT NULL REFERENCES bills_of_materials(id) ON DELETE CASCADE,
  item_code VARCHAR(50),
  name VARCHAR(255) NOT NULL,
  description TEXT,
  quantity DECIMAL(18,4) NOT NULL DEFAULT 1,
  unit VARCHAR(20),
  unit_cost DECIMAL(18,4) DEFAULT 0,
  total_cost DECIMAL(18,2) DEFAULT 0,
  lead_time_days INT DEFAULT 0,
  supplier_id UUID REFERENCES contacts(id),
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE work_orders (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_number VARCHAR(50) NOT NULL UNIQUE,
  bom_id UUID REFERENCES bills_of_materials(id),
  product_id UUID NOT NULL REFERENCES products(id),
  quantity DECIMAL(18,4) NOT NULL DEFAULT 1,
  quantity_completed DECIMAL(18,4) DEFAULT 0,
  status work_order_status NOT NULL DEFAULT 'draft',
  priority work_order_priority NOT NULL DEFAULT 'medium',
  planned_start_date DATE,
  planned_end_date DATE,
  actual_start_date DATE,
  actual_end_date DATE,
  estimated_cost DECIMAL(18,2) DEFAULT 0,
  actual_cost DECIMAL(18,2) DEFAULT 0,
  assigned_to VARCHAR(255),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE work_order_operations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  work_order_id UUID NOT NULL REFERENCES work_orders(id) ON DELETE CASCADE,
  sequence INT NOT NULL DEFAULT 1,
  name VARCHAR(255) NOT NULL,
  work_center_id UUID REFERENCES work_centers(id),
  planned_hours DECIMAL(10,2) DEFAULT 0,
  actual_hours DECIMAL(10,2) DEFAULT 0,
  status operation_status NOT NULL DEFAULT 'pending',
  assigned_to VARCHAR(255),
  notes TEXT,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE quality_checks (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  check_number VARCHAR(50) NOT NULL UNIQUE,
  work_order_id UUID NOT NULL REFERENCES work_orders(id),
  batch_number VARCHAR(50),
  inspection_date DATE NOT NULL,
  inspector_id UUID,
  inspector_name VARCHAR(255),
  status qc_status NOT NULL DEFAULT 'pending',
  overall_result qc_result NOT NULL DEFAULT 'pending',
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE quality_check_items (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  quality_check_id UUID NOT NULL REFERENCES quality_checks(id) ON DELETE CASCADE,
  parameter VARCHAR(255) NOT NULL,
  specification TEXT,
  actual_value TEXT,
  result qc_result NOT NULL DEFAULT 'pending',
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 12. CRM (Leads, Deals, Pipeline)
-- ============================================================

CREATE TABLE pipeline_stages (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(100) NOT NULL,
  stage deal_stage NOT NULL UNIQUE,
  color VARCHAR(50),
  sort_order INT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE leads (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  phone VARCHAR(50),
  company VARCHAR(255),
  source VARCHAR(100),
  status lead_status NOT NULL DEFAULT 'new',
  score INT DEFAULT 0,
  assigned_to VARCHAR(255),
  assigned_to_id UUID,
  notes TEXT,
  converted_deal_id UUID,
  converted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE deals (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  title VARCHAR(255) NOT NULL,
  value DECIMAL(18,2) NOT NULL DEFAULT 0,
  currency_id UUID REFERENCES currencies(id),
  stage deal_stage NOT NULL DEFAULT 'lead',
  probability INT DEFAULT 0,
  contact_id UUID REFERENCES contacts(id),
  assigned_to VARCHAR(255),
  assigned_to_id UUID,
  expected_close_date DATE,
  actual_close_date DATE,
  tags TEXT[] DEFAULT '{}',
  notes TEXT,
  lost_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE deal_activities (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  deal_id UUID NOT NULL REFERENCES deals(id) ON DELETE CASCADE,
  type activity_type NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  user_name VARCHAR(255),
  user_id UUID,
  is_completed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 13. EMPLOYEES & HR
-- ============================================================

CREATE TABLE departments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(100) NOT NULL,
  code VARCHAR(20) NOT NULL UNIQUE,
  parent_id UUID REFERENCES departments(id),
  manager_id UUID,
  color VARCHAR(50),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE positions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  title VARCHAR(255) NOT NULL,
  department_id UUID REFERENCES departments(id),
  level VARCHAR(50),
  min_salary DECIMAL(18,2),
  max_salary DECIMAL(18,2),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE employees (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  employee_id VARCHAR(20) NOT NULL UNIQUE,
  user_id UUID,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL,
  work_email VARCHAR(255),
  phone VARCHAR(50),
  avatar_url TEXT,
  date_of_birth DATE,
  sin_last_three VARCHAR(3),
  job_title VARCHAR(255),
  department_id UUID REFERENCES departments(id),
  position_id UUID REFERENCES positions(id),
  manager_id UUID REFERENCES employees(id),
  employment_type employment_type NOT NULL DEFAULT 'full-time',
  status employment_status NOT NULL DEFAULT 'active',
  hire_date DATE NOT NULL,
  termination_date DATE,
  probation_end_date DATE,
  salary DECIMAL(18,2) NOT NULL DEFAULT 0,
  currency_id UUID REFERENCES currencies(id),
  pay_frequency pay_period DEFAULT 'semi-monthly',
  location VARCHAR(255),
  address_line1 VARCHAR(255),
  address_line2 VARCHAR(255),
  city VARCHAR(100),
  province VARCHAR(100),
  postal_code VARCHAR(20),
  country VARCHAR(100) DEFAULT 'Canada',
  emergency_contact_name VARCHAR(255),
  emergency_contact_relationship VARCHAR(100),
  emergency_contact_phone VARCHAR(50),
  skills TEXT[] DEFAULT '{}',
  bio TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Back-reference manager in departments
ALTER TABLE departments ADD CONSTRAINT fk_dept_manager FOREIGN KEY (manager_id) REFERENCES employees(id);

-- ============================================================
-- 14. PAYROLL
-- ============================================================

CREATE TABLE payroll_runs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(255) NOT NULL,
  period pay_period NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  pay_date DATE NOT NULL,
  status payroll_status NOT NULL DEFAULT 'draft',
  total_employees INT DEFAULT 0,
  total_gross DECIMAL(18,2) DEFAULT 0,
  total_deductions DECIMAL(18,2) DEFAULT 0,
  total_net DECIMAL(18,2) DEFAULT 0,
  total_employer_contributions DECIMAL(18,2) DEFAULT 0,
  currency_id UUID REFERENCES currencies(id),
  notes TEXT,
  created_by VARCHAR(255),
  processed_by VARCHAR(255),
  processed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE payslips (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  payroll_run_id UUID NOT NULL REFERENCES payroll_runs(id) ON DELETE CASCADE,
  employee_id UUID NOT NULL REFERENCES employees(id),
  status payslip_status NOT NULL DEFAULT 'draft',
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  pay_date DATE NOT NULL,
  gross_pay DECIMAL(18,2) NOT NULL DEFAULT 0,
  total_deductions DECIMAL(18,2) NOT NULL DEFAULT 0,
  net_pay DECIMAL(18,2) NOT NULL DEFAULT 0,
  ytd_gross DECIMAL(18,2) DEFAULT 0,
  ytd_net DECIMAL(18,2) DEFAULT 0,
  ytd_cpp DECIMAL(18,2) DEFAULT 0,
  ytd_ei DECIMAL(18,2) DEFAULT 0,
  ytd_tax DECIMAL(18,2) DEFAULT 0,
  currency_id UUID REFERENCES currencies(id),
  notes TEXT,
  approved_by VARCHAR(255),
  approved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE payslip_earnings (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  payslip_id UUID NOT NULL REFERENCES payslips(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  type earning_type NOT NULL,
  amount DECIMAL(18,2) NOT NULL,
  hours DECIMAL(10,2),
  rate DECIMAL(18,4),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE payslip_deductions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  payslip_id UUID NOT NULL REFERENCES payslips(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  type deduction_type NOT NULL,
  amount DECIMAL(18,2) NOT NULL,
  percentage DECIMAL(6,4),
  is_employer_portion BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE benefit_plans (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(255) NOT NULL,
  type VARCHAR(50) NOT NULL,
  description TEXT,
  employer_contribution DECIMAL(6,4) DEFAULT 0,
  employee_contribution DECIMAL(6,4) DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE employee_benefits (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  benefit_plan_id UUID NOT NULL REFERENCES benefit_plans(id),
  enrollment_date DATE NOT NULL,
  end_date DATE,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 15. PROJECTS (Tasks, Milestones, Time Tracking)
-- ============================================================

CREATE TABLE projects (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  client_id UUID REFERENCES contacts(id),
  status project_status NOT NULL DEFAULT 'planning',
  priority project_priority NOT NULL DEFAULT 'medium',
  start_date DATE,
  end_date DATE,
  budget DECIMAL(18,2) DEFAULT 0,
  spent DECIMAL(18,2) DEFAULT 0,
  progress INT DEFAULT 0,
  manager_id UUID REFERENCES employees(id),
  tags TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE project_members (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  employee_id UUID NOT NULL REFERENCES employees(id),
  role VARCHAR(100) DEFAULT 'member',
  joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(project_id, employee_id)
);

CREATE TABLE tasks (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  status task_status NOT NULL DEFAULT 'todo',
  priority work_order_priority NOT NULL DEFAULT 'medium',
  assignee_id UUID REFERENCES employees(id),
  parent_task_id UUID REFERENCES tasks(id),
  due_date DATE,
  estimated_hours DECIMAL(10,2),
  actual_hours DECIMAL(10,2),
  tags TEXT[] DEFAULT '{}',
  sort_order INT DEFAULT 0,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE milestones (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  due_date DATE NOT NULL,
  status milestone_status NOT NULL DEFAULT 'pending',
  completed_date DATE,
  deliverables TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE time_entries (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  project_id UUID NOT NULL REFERENCES projects(id),
  task_id UUID REFERENCES tasks(id),
  employee_id UUID NOT NULL REFERENCES employees(id),
  date DATE NOT NULL,
  hours DECIMAL(10,2) NOT NULL,
  description TEXT,
  billable BOOLEAN DEFAULT TRUE,
  hourly_rate DECIMAL(18,4),
  status time_entry_status NOT NULL DEFAULT 'draft',
  approved_by UUID REFERENCES employees(id),
  approved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 16. AUDIT LOG
-- ============================================================

CREATE TABLE audit_log (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  table_name VARCHAR(100) NOT NULL,
  record_id UUID NOT NULL,
  action VARCHAR(20) NOT NULL,
  old_values JSONB,
  new_values JSONB,
  changed_fields TEXT[],
  user_id UUID,
  user_email VARCHAR(255),
  ip_address INET,
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 17. NOTIFICATIONS
-- ============================================================

CREATE TABLE notifications (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID,
  type notification_type NOT NULL DEFAULT 'info',
  channel notification_channel DEFAULT 'in_app',
  title VARCHAR(255) NOT NULL,
  message TEXT,
  link VARCHAR(500),
  is_read BOOLEAN DEFAULT FALSE,
  read_at TIMESTAMPTZ,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 18. FILE ATTACHMENTS
-- ============================================================

CREATE TABLE file_attachments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  table_name VARCHAR(100) NOT NULL,
  record_id UUID NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_path TEXT NOT NULL,
  file_size INT,
  mime_type VARCHAR(100),
  uploaded_by UUID,
  uploaded_by_name VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- INDEXES
-- ============================================================

-- Contacts
CREATE INDEX idx_contacts_type ON contacts(type);
CREATE INDEX idx_contacts_email ON contacts(email);
CREATE INDEX idx_contacts_name ON contacts(name);
CREATE INDEX idx_contacts_is_active ON contacts(is_active);
CREATE INDEX idx_contact_addresses_contact ON contact_addresses(contact_id);

-- Accounting
CREATE INDEX idx_coa_type ON chart_of_accounts(type);
CREATE INDEX idx_coa_code ON chart_of_accounts(code);
CREATE INDEX idx_journal_entries_date ON journal_entries(date);
CREATE INDEX idx_journal_entries_posted ON journal_entries(is_posted);
CREATE INDEX idx_journal_lines_entry ON journal_lines(journal_entry_id);
CREATE INDEX idx_journal_lines_account ON journal_lines(account_id);

-- Invoices
CREATE INDEX idx_invoices_customer ON invoices(customer_id);
CREATE INDEX idx_invoices_status ON invoices(status);
CREATE INDEX idx_invoices_due_date ON invoices(due_date);
CREATE INDEX idx_invoices_issue_date ON invoices(issue_date);
CREATE INDEX idx_invoice_items_invoice ON invoice_line_items(invoice_id);
CREATE INDEX idx_invoice_payments_invoice ON invoice_payments(invoice_id);

-- Bills
CREATE INDEX idx_bills_vendor ON bills(vendor_id);
CREATE INDEX idx_bills_status ON bills(status);
CREATE INDEX idx_bills_due_date ON bills(due_date);
CREATE INDEX idx_bill_items_bill ON bill_line_items(bill_id);

-- Banking
CREATE INDEX idx_bank_txn_account ON bank_transactions(bank_account_id);
CREATE INDEX idx_bank_txn_date ON bank_transactions(date);
CREATE INDEX idx_bank_txn_reconciliation ON bank_transactions(reconciliation_status);

-- Products / Inventory
CREATE INDEX idx_products_sku ON products(sku);
CREATE INDEX idx_products_category ON products(category_id);
CREATE INDEX idx_products_status ON products(status);
CREATE INDEX idx_products_stock ON products(stock_quantity);
CREATE INDEX idx_stock_movements_product ON stock_movements(product_id);
CREATE INDEX idx_stock_movements_date ON stock_movements(created_at);

-- Warehouses
CREATE INDEX idx_warehouse_stock_wh ON warehouse_stock(warehouse_id);
CREATE INDEX idx_warehouse_stock_product ON warehouse_stock(product_id);
CREATE INDEX idx_stock_transfers_status ON stock_transfers(status);

-- Sales
CREATE INDEX idx_sales_orders_customer ON sales_orders(customer_id);
CREATE INDEX idx_sales_orders_status ON sales_orders(status);
CREATE INDEX idx_sales_orders_date ON sales_orders(order_date);
CREATE INDEX idx_quotes_customer ON quotes(customer_id);
CREATE INDEX idx_quotes_status ON quotes(status);

-- Purchases
CREATE INDEX idx_po_vendor ON purchase_orders(vendor_id);
CREATE INDEX idx_po_status ON purchase_orders(status);
CREATE INDEX idx_goods_receipts_po ON goods_receipts(purchase_order_id);

-- Manufacturing
CREATE INDEX idx_work_orders_status ON work_orders(status);
CREATE INDEX idx_work_orders_product ON work_orders(product_id);
CREATE INDEX idx_work_orders_priority ON work_orders(priority);
CREATE INDEX idx_bom_product ON bills_of_materials(product_id);
CREATE INDEX idx_quality_checks_wo ON quality_checks(work_order_id);

-- CRM
CREATE INDEX idx_leads_status ON leads(status);
CREATE INDEX idx_deals_stage ON deals(stage);
CREATE INDEX idx_deals_contact ON deals(contact_id);
CREATE INDEX idx_deal_activities_deal ON deal_activities(deal_id);

-- Employees
CREATE INDEX idx_employees_dept ON employees(department_id);
CREATE INDEX idx_employees_status ON employees(status);
CREATE INDEX idx_employees_manager ON employees(manager_id);
CREATE INDEX idx_employees_employee_id ON employees(employee_id);

-- Payroll
CREATE INDEX idx_payroll_runs_status ON payroll_runs(status);
CREATE INDEX idx_payroll_runs_dates ON payroll_runs(period_start, period_end);
CREATE INDEX idx_payslips_employee ON payslips(employee_id);
CREATE INDEX idx_payslips_run ON payslips(payroll_run_id);

-- Projects
CREATE INDEX idx_projects_status ON projects(status);
CREATE INDEX idx_projects_client ON projects(client_id);
CREATE INDEX idx_tasks_project ON tasks(project_id);
CREATE INDEX idx_tasks_assignee ON tasks(assignee_id);
CREATE INDEX idx_tasks_status ON tasks(status);
CREATE INDEX idx_milestones_project ON milestones(project_id);
CREATE INDEX idx_time_entries_project ON time_entries(project_id);
CREATE INDEX idx_time_entries_employee ON time_entries(employee_id);
CREATE INDEX idx_time_entries_date ON time_entries(date);

-- Audit & Notifications
CREATE INDEX idx_audit_table_record ON audit_log(table_name, record_id);
CREATE INDEX idx_audit_created ON audit_log(created_at);
CREATE INDEX idx_notifications_user ON notifications(user_id);
CREATE INDEX idx_notifications_read ON notifications(is_read);
CREATE INDEX idx_file_attachments_record ON file_attachments(table_name, record_id);

-- ============================================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================================

-- Enable RLS on all tables
ALTER TABLE currencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE company_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE tax_rates ENABLE ROW LEVEL SECURITY;
ALTER TABLE fiscal_years ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE chart_of_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE journal_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE journal_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_line_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE bill_line_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE bill_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE bank_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE bank_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE reconciliation_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE units_of_measure ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE warehouses ENABLE ROW LEVEL SECURITY;
ALTER TABLE warehouse_zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE bin_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE warehouse_stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_transfers ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_transfer_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE quote_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE goods_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE goods_receipt_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_centers ENABLE ROW LEVEL SECURITY;
ALTER TABLE bills_of_materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE bom_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_order_operations ENABLE ROW LEVEL SECURITY;
ALTER TABLE quality_checks ENABLE ROW LEVEL SECURITY;
ALTER TABLE quality_check_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE pipeline_stages ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE deals ENABLE ROW LEVEL SECURITY;
ALTER TABLE deal_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE positions ENABLE ROW LEVEL SECURITY;
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE payslips ENABLE ROW LEVEL SECURITY;
ALTER TABLE payslip_earnings ENABLE ROW LEVEL SECURITY;
ALTER TABLE payslip_deductions ENABLE ROW LEVEL SECURITY;
ALTER TABLE benefit_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee_benefits ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE time_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE file_attachments ENABLE ROW LEVEL SECURITY;

-- Authenticated users can read/write all data (single-tenant ERP)
-- In production, add org_id column and scope policies per org

CREATE POLICY "Authenticated users full access" ON currencies FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON company_settings FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON tax_rates FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON fiscal_years FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON system_settings FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON contacts FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON contact_addresses FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON contact_activities FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON chart_of_accounts FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON journal_entries FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON journal_lines FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON invoices FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON invoice_line_items FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON invoice_payments FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON bills FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON bill_line_items FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON bill_payments FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON bank_accounts FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON bank_transactions FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON reconciliation_rules FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON product_categories FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON units_of_measure FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON products FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON stock_movements FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON warehouses FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON warehouse_zones FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON bin_locations FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON warehouse_stock FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON stock_transfers FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON stock_transfer_items FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON quotes FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON quote_items FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON sales_orders FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON sales_order_items FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON purchase_orders FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON purchase_order_items FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON goods_receipts FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON goods_receipt_items FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON work_centers FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON bills_of_materials FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON bom_items FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON work_orders FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON work_order_operations FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON quality_checks FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON quality_check_items FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON pipeline_stages FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON leads FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON deals FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON deal_activities FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON departments FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON positions FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON employees FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON payroll_runs FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON payslips FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON payslip_earnings FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON payslip_deductions FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON benefit_plans FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON employee_benefits FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON projects FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON project_members FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON tasks FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON milestones FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON time_entries FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON audit_log FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON notifications FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users full access" ON file_attachments FOR ALL USING (auth.role() = 'authenticated');

-- ============================================================
-- TRIGGERS — updated_at auto-refresh
-- ============================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply to all tables with updated_at
DO $$
DECLARE
  tbl TEXT;
BEGIN
  FOR tbl IN
    SELECT table_name FROM information_schema.columns
    WHERE column_name = 'updated_at' AND table_schema = 'public'
  LOOP
    EXECUTE format('
      CREATE TRIGGER set_updated_at
      BEFORE UPDATE ON %I
      FOR EACH ROW
      EXECUTE FUNCTION update_updated_at_column();
    ', tbl);
  END LOOP;
END;
$$;

-- ============================================================
-- AUDIT TRIGGER FUNCTION
-- ============================================================

CREATE OR REPLACE FUNCTION audit_trigger_func()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO audit_log (table_name, record_id, action, new_values, user_id, user_email)
    VALUES (TG_TABLE_NAME, NEW.id, 'INSERT', to_jsonb(NEW), auth.uid(), current_setting('request.jwt.claims', true)::json->>'email');
    RETURN NEW;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO audit_log (table_name, record_id, action, old_values, new_values, user_id, user_email)
    VALUES (TG_TABLE_NAME, NEW.id, 'UPDATE', to_jsonb(OLD), to_jsonb(NEW), auth.uid(), current_setting('request.jwt.claims', true)::json->>'email');
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO audit_log (table_name, record_id, action, old_values, user_id, user_email)
    VALUES (TG_TABLE_NAME, OLD.id, 'DELETE', to_jsonb(OLD), auth.uid(), current_setting('request.jwt.claims', true)::json->>'email');
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Apply audit triggers to key tables
CREATE TRIGGER audit_contacts AFTER INSERT OR UPDATE OR DELETE ON contacts FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();
CREATE TRIGGER audit_invoices AFTER INSERT OR UPDATE OR DELETE ON invoices FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();
CREATE TRIGGER audit_bills AFTER INSERT OR UPDATE OR DELETE ON bills FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();
CREATE TRIGGER audit_sales_orders AFTER INSERT OR UPDATE OR DELETE ON sales_orders FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();
CREATE TRIGGER audit_purchase_orders AFTER INSERT OR UPDATE OR DELETE ON purchase_orders FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();
CREATE TRIGGER audit_products AFTER INSERT OR UPDATE OR DELETE ON products FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();
CREATE TRIGGER audit_work_orders AFTER INSERT OR UPDATE OR DELETE ON work_orders FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();
CREATE TRIGGER audit_deals AFTER INSERT OR UPDATE OR DELETE ON deals FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();
CREATE TRIGGER audit_employees AFTER INSERT OR UPDATE OR DELETE ON employees FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();
CREATE TRIGGER audit_payroll_runs AFTER INSERT OR UPDATE OR DELETE ON payroll_runs FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();
CREATE TRIGGER audit_journal_entries AFTER INSERT OR UPDATE OR DELETE ON journal_entries FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();

-- ============================================================
-- SEED DATA — Canadian defaults
-- ============================================================

-- Currencies
INSERT INTO currencies (code, name, symbol, exchange_rate, is_base, is_active) VALUES
  ('CAD', 'Canadian Dollar', '$', 1.000000, TRUE, TRUE),
  ('USD', 'US Dollar', 'US$', 0.740000, FALSE, TRUE),
  ('EUR', 'Euro', '€', 0.680000, FALSE, TRUE),
  ('GBP', 'British Pound', '£', 0.580000, FALSE, TRUE);

-- Canadian Tax Rates
INSERT INTO tax_rates (name, code, rate, description, region) VALUES
  ('GST', 'GST', 0.0500, 'Goods and Services Tax', 'Federal'),
  ('HST Ontario', 'HST-ON', 0.1300, 'Harmonized Sales Tax - Ontario', 'Ontario'),
  ('HST Nova Scotia', 'HST-NS', 0.1500, 'Harmonized Sales Tax - Nova Scotia', 'Nova Scotia'),
  ('HST New Brunswick', 'HST-NB', 0.1500, 'Harmonized Sales Tax - New Brunswick', 'New Brunswick'),
  ('PST British Columbia', 'PST-BC', 0.0700, 'Provincial Sales Tax - BC', 'British Columbia'),
  ('QST Quebec', 'QST-QC', 0.09975, 'Quebec Sales Tax', 'Quebec'),
  ('PST Saskatchewan', 'PST-SK', 0.0600, 'Provincial Sales Tax - SK', 'Saskatchewan'),
  ('PST Manitoba', 'PST-MB', 0.0700, 'Retail Sales Tax - Manitoba', 'Manitoba'),
  ('Zero Rated', 'ZERO', 0.0000, 'Zero-rated supplies', 'Federal'),
  ('Exempt', 'EXEMPT', 0.0000, 'Tax-exempt supplies', 'Federal');

-- Units of Measure
INSERT INTO units_of_measure (name, abbreviation, category) VALUES
  ('Piece', 'pcs', 'Count'),
  ('Box', 'box', 'Count'),
  ('Case', 'case', 'Count'),
  ('Set', 'set', 'Count'),
  ('Kilogram', 'kg', 'Weight'),
  ('Pound', 'lb', 'Weight'),
  ('Litre', 'L', 'Volume'),
  ('Metre', 'm', 'Length'),
  ('Square Metre', 'm²', 'Area'),
  ('Hour', 'hr', 'Time'),
  ('Ream', 'ream', 'Count'),
  ('Licence', 'lic', 'Count'),
  ('Each', 'ea', 'Count');

-- Pipeline Stages
INSERT INTO pipeline_stages (name, stage, color, sort_order) VALUES
  ('Lead', 'lead', 'bg-gray-500', 1),
  ('Qualified', 'qualified', 'bg-blue-500', 2),
  ('Proposal', 'proposal', 'bg-purple-500', 3),
  ('Negotiation', 'negotiation', 'bg-yellow-500', 4),
  ('Won', 'won', 'bg-green-500', 5),
  ('Lost', 'lost', 'bg-red-500', 6);

-- Done!
