import { Contact, ContactStats } from '@/types/contacts'

export const mockContacts: Contact[] = [
  {
    id: 'c1',
    type: 'customer',
    category: 'company',
    name: 'Acme Corporation',
    email: 'contact@acme.com',
    phone: '+1 (555) 123-4567',
    website: 'https://acme.com',
    addresses: [
      {
        id: 'a1',
        type: 'billing',
        line1: '123 Business Ave',
        city: 'San Francisco',
        state: 'CA',
        postalCode: '94102',
        country: 'USA',
        isPrimary: true,
      },
    ],
    tags: ['enterprise', 'tech', 'priority'],
    notes: 'Key account - requires dedicated support',
    createdAt: '2024-01-15',
    updatedAt: '2024-02-10',
    totalRevenue: 125000,
    totalOrders: 45,
    lastContactedAt: '2024-02-10',
    activities: [
      { id: 'act1', type: 'meeting', title: 'Q1 Review Meeting', date: '2024-02-10', user: 'John Doe' },
      { id: 'act2', type: 'invoice', title: 'Invoice #1234 Sent', date: '2024-02-08', user: 'System' },
      { id: 'act3', type: 'payment', title: 'Payment Received - $15,000', date: '2024-02-05', user: 'System' },
    ],
  },
  {
    id: 'c2',
    type: 'customer',
    category: 'individual',
    name: 'Sarah Johnson',
    email: 'sarah.j@email.com',
    phone: '+1 (555) 234-5678',
    company: 'Johnson Consulting',
    jobTitle: 'CEO',
    addresses: [
      {
        id: 'a2',
        type: 'billing',
        line1: '456 Oak Street',
        city: 'Austin',
        state: 'TX',
        postalCode: '78701',
        country: 'USA',
        isPrimary: true,
      },
    ],
    tags: ['consulting', 'premium'],
    createdAt: '2024-02-01',
    updatedAt: '2024-02-12',
    totalRevenue: 35000,
    totalOrders: 12,
    lastContactedAt: '2024-02-12',
    activities: [
      { id: 'act4', type: 'call', title: 'Follow-up call', date: '2024-02-12', user: 'Jane Smith' },
      { id: 'act5', type: 'email', title: 'Proposal sent', date: '2024-02-10', user: 'Jane Smith' },
    ],
  },
  {
    id: 'c3',
    type: 'vendor',
    category: 'company',
    name: 'TechSupply Inc',
    email: 'orders@techsupply.com',
    phone: '+1 (555) 345-6789',
    website: 'https://techsupply.com',
    addresses: [
      {
        id: 'a3',
        type: 'shipping',
        line1: '789 Industrial Blvd',
        city: 'Chicago',
        state: 'IL',
        postalCode: '60601',
        country: 'USA',
        isPrimary: true,
      },
    ],
    tags: ['hardware', 'supplier'],
    createdAt: '2023-06-20',
    updatedAt: '2024-02-08',
    totalRevenue: 0,
    totalOrders: 28,
    lastContactedAt: '2024-02-08',
    activities: [
      { id: 'act6', type: 'order', title: 'PO #789 Created', date: '2024-02-08', user: 'Mike Wilson' },
    ],
  },
  {
    id: 'c4',
    type: 'both',
    category: 'company',
    name: 'GlobalTech Partners',
    email: 'info@globaltech.com',
    phone: '+1 (555) 456-7890',
    website: 'https://globaltech.com',
    addresses: [
      {
        id: 'a4',
        type: 'billing',
        line1: '100 Partner Way',
        city: 'Seattle',
        state: 'WA',
        postalCode: '98101',
        country: 'USA',
        isPrimary: true,
      },
    ],
    tags: ['partner', 'strategic'],
    notes: 'Both customer and vendor - joint ventures',
    createdAt: '2023-03-10',
    updatedAt: '2024-02-14',
    totalRevenue: 250000,
    totalOrders: 67,
    lastContactedAt: '2024-02-14',
    activities: [
      { id: 'act7', type: 'meeting', title: 'Partnership Review', date: '2024-02-14', user: 'CEO' },
    ],
  },
  {
    id: 'c5',
    type: 'customer',
    category: 'individual',
    name: 'Michael Chen',
    email: 'mchen@startup.io',
    phone: '+1 (555) 567-8901',
    company: 'Chen Ventures',
    jobTitle: 'Founder',
    addresses: [],
    tags: ['startup', 'referral'],
    createdAt: '2024-02-10',
    updatedAt: '2024-02-13',
    totalRevenue: 8500,
    totalOrders: 3,
    lastContactedAt: '2024-02-13',
    activities: [
      { id: 'act8', type: 'email', title: 'Welcome email sent', date: '2024-02-10', user: 'System' },
    ],
  },
  {
    id: 'c6',
    type: 'vendor',
    category: 'company',
    name: 'Office Solutions Ltd',
    email: 'sales@officesolutions.com',
    phone: '+1 (555) 678-9012',
    addresses: [
      {
        id: 'a5',
        type: 'billing',
        line1: '222 Supply Lane',
        city: 'Denver',
        state: 'CO',
        postalCode: '80202',
        country: 'USA',
        isPrimary: true,
      },
    ],
    tags: ['office', 'supplies'],
    createdAt: '2023-09-15',
    updatedAt: '2024-01-20',
    totalRevenue: 0,
    totalOrders: 15,
    activities: [],
  },
]

export const mockContactStats: ContactStats = {
  total: 156,
  customers: 98,
  vendors: 45,
  newThisMonth: 12,
  activeDeals: 23,
}
