import { Deal, Lead, PipelineStage, CRMStats, DealStage } from '@/types/crm'

export const mockLeads: Lead[] = [
  {
    id: 'l1',
    name: 'James Wilson',
    email: 'jwilson@bigcorp.com',
    phone: '+1 (555) 111-2222',
    company: 'BigCorp Industries',
    source: 'Website',
    status: 'new',
    score: 85,
    assignedTo: 'Jane Smith',
    createdAt: '2024-02-14',
  },
  {
    id: 'l2',
    name: 'Emily Davis',
    email: 'emily@startupx.io',
    company: 'StartupX',
    source: 'LinkedIn',
    status: 'contacted',
    score: 72,
    assignedTo: 'John Doe',
    createdAt: '2024-02-12',
  },
  {
    id: 'l3',
    name: 'Robert Brown',
    email: 'rbrown@enterprise.com',
    phone: '+1 (555) 333-4444',
    company: 'Enterprise Solutions',
    source: 'Referral',
    status: 'qualified',
    score: 95,
    assignedTo: 'Jane Smith',
    createdAt: '2024-02-10',
  },
]

export const mockDeals: Deal[] = [
  {
    id: 'd1',
    title: 'Enterprise License Deal',
    value: 75000,
    currency: 'USD',
    stage: 'negotiation',
    probability: 75,
    contactId: 'c1',
    contactName: 'Acme Corporation',
    contactEmail: 'contact@acme.com',
    company: 'Acme Corporation',
    assignedTo: 'u1',
    assignedToName: 'John Doe',
    expectedCloseDate: '2024-03-15',
    createdAt: '2024-01-20',
    updatedAt: '2024-02-14',
    activities: [
      { id: 'da1', type: 'meeting', title: 'Contract Review', date: '2024-02-14', user: 'John Doe', completed: true },
      { id: 'da2', type: 'email', title: 'Send revised proposal', date: '2024-02-16', user: 'John Doe', completed: false },
    ],
    tags: ['enterprise', 'priority'],
  },
  {
    id: 'd2',
    title: 'SaaS Implementation',
    value: 45000,
    currency: 'USD',
    stage: 'proposal',
    probability: 50,
    contactId: 'c2',
    contactName: 'Sarah Johnson',
    contactEmail: 'sarah.j@email.com',
    company: 'Johnson Consulting',
    assignedTo: 'u2',
    assignedToName: 'Jane Smith',
    expectedCloseDate: '2024-03-30',
    createdAt: '2024-02-01',
    updatedAt: '2024-02-13',
    activities: [
      { id: 'da3', type: 'call', title: 'Discovery Call', date: '2024-02-01', user: 'Jane Smith', completed: true },
      { id: 'da4', type: 'task', title: 'Prepare demo', date: '2024-02-15', user: 'Jane Smith', completed: false },
    ],
    tags: ['saas'],
  },
  {
    id: 'd3',
    title: 'Annual Support Contract',
    value: 25000,
    currency: 'USD',
    stage: 'qualified',
    probability: 30,
    contactId: 'c4',
    contactName: 'GlobalTech Partners',
    contactEmail: 'info@globaltech.com',
    company: 'GlobalTech Partners',
    assignedTo: 'u1',
    assignedToName: 'John Doe',
    expectedCloseDate: '2024-04-15',
    createdAt: '2024-02-10',
    updatedAt: '2024-02-12',
    activities: [],
    tags: ['support', 'renewal'],
  },
  {
    id: 'd4',
    title: 'Startup Package',
    value: 12000,
    currency: 'USD',
    stage: 'lead',
    probability: 10,
    contactId: 'c5',
    contactName: 'Michael Chen',
    contactEmail: 'mchen@startup.io',
    company: 'Chen Ventures',
    assignedTo: 'u2',
    assignedToName: 'Jane Smith',
    expectedCloseDate: '2024-05-01',
    createdAt: '2024-02-13',
    updatedAt: '2024-02-13',
    activities: [],
    tags: ['startup'],
  },
  {
    id: 'd5',
    title: 'Custom Integration Project',
    value: 95000,
    currency: 'USD',
    stage: 'won',
    probability: 100,
    contactId: 'c1',
    contactName: 'Acme Corporation',
    contactEmail: 'contact@acme.com',
    company: 'Acme Corporation',
    assignedTo: 'u1',
    assignedToName: 'John Doe',
    expectedCloseDate: '2024-02-01',
    createdAt: '2023-12-01',
    updatedAt: '2024-02-01',
    activities: [],
    tags: ['integration', 'won'],
  },
  {
    id: 'd6',
    title: 'Legacy Migration',
    value: 55000,
    currency: 'USD',
    stage: 'lost',
    probability: 0,
    contactId: 'c4',
    contactName: 'GlobalTech Partners',
    contactEmail: 'info@globaltech.com',
    company: 'GlobalTech Partners',
    assignedTo: 'u2',
    assignedToName: 'Jane Smith',
    expectedCloseDate: '2024-01-15',
    createdAt: '2023-11-01',
    updatedAt: '2024-01-20',
    activities: [],
    tags: ['migration', 'lost'],
    notes: 'Lost to competitor - pricing concerns',
  },
]

export const stageConfig: Record<DealStage, { name: string; color: string }> = {
  lead: { name: 'Lead', color: 'bg-gray-500' },
  qualified: { name: 'Qualified', color: 'bg-blue-500' },
  proposal: { name: 'Proposal', color: 'bg-purple-500' },
  negotiation: { name: 'Negotiation', color: 'bg-yellow-500' },
  won: { name: 'Won', color: 'bg-green-500' },
  lost: { name: 'Lost', color: 'bg-red-500' },
}

export function getPipelineStages(): PipelineStage[] {
  const stages: DealStage[] = ['lead', 'qualified', 'proposal', 'negotiation', 'won', 'lost']
  
  return stages.map(stage => {
    const stageDeals = mockDeals.filter(d => d.stage === stage)
    return {
      id: stage,
      name: stageConfig[stage].name,
      color: stageConfig[stage].color,
      deals: stageDeals,
      totalValue: stageDeals.reduce((sum, d) => sum + d.value, 0),
    }
  })
}

export const mockCRMStats: CRMStats = {
  totalDeals: 24,
  totalValue: 485000,
  wonDeals: 8,
  wonValue: 195000,
  lostDeals: 3,
  conversionRate: 42,
  avgDealSize: 24250,
  pipelineValue: 157000,
}
