import { Employee, Department, OrgNode, EmployeeStats } from '@/types/employees'

export const mockDepartments: Department[] = [
  { id: 'dept1', name: 'Engineering', code: 'ENG', managerId: 'e1', managerName: 'John Doe', employeeCount: 25, color: 'bg-blue-500' },
  { id: 'dept2', name: 'Sales', code: 'SALES', managerId: 'e3', managerName: 'Sarah Johnson', employeeCount: 15, color: 'bg-green-500' },
  { id: 'dept3', name: 'Marketing', code: 'MKT', managerId: 'e5', managerName: 'Emily Chen', employeeCount: 10, color: 'bg-purple-500' },
  { id: 'dept4', name: 'Human Resources', code: 'HR', managerId: 'e7', managerName: 'Michael Brown', employeeCount: 5, color: 'bg-yellow-500' },
  { id: 'dept5', name: 'Finance', code: 'FIN', managerId: 'e8', managerName: 'Lisa Wang', employeeCount: 8, color: 'bg-red-500' },
  { id: 'dept6', name: 'Operations', code: 'OPS', managerId: 'e9', managerName: 'David Miller', employeeCount: 12, color: 'bg-orange-500' },
]

export const mockEmployees: Employee[] = [
  {
    id: 'e0',
    employeeId: 'EMP-001',
    firstName: 'Robert',
    lastName: 'Anderson',
    email: 'randerson@company.com',
    phone: '+1 (555) 000-0001',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Robert',
    jobTitle: 'Chief Executive Officer',
    department: 'Executive',
    departmentId: 'dept0',
    employmentType: 'full-time',
    status: 'active',
    hireDate: '2018-01-15',
    salary: 350000,
    currency: 'USD',
    location: 'San Francisco, CA',
    workEmail: 'ceo@company.com',
    skills: ['Leadership', 'Strategy', 'Business Development'],
    bio: 'Founder and CEO with 20+ years of experience in tech.',
    directReports: ['e1', 'e3', 'e5', 'e7', 'e8', 'e9'],
  },
  {
    id: 'e1',
    employeeId: 'EMP-002',
    firstName: 'John',
    lastName: 'Doe',
    email: 'jdoe@company.com',
    phone: '+1 (555) 100-0001',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    jobTitle: 'VP of Engineering',
    department: 'Engineering',
    departmentId: 'dept1',
    managerId: 'e0',
    managerName: 'Robert Anderson',
    employmentType: 'full-time',
    status: 'active',
    hireDate: '2019-03-20',
    salary: 220000,
    currency: 'USD',
    location: 'San Francisco, CA',
    workEmail: 'john.doe@company.com',
    skills: ['Software Architecture', 'Team Leadership', 'Python', 'Go'],
    bio: 'Engineering leader focused on building scalable systems.',
    directReports: ['e2', 'e10', 'e11'],
  },
  {
    id: 'e2',
    employeeId: 'EMP-003',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jsmith@company.com',
    phone: '+1 (555) 100-0002',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    jobTitle: 'Senior Software Engineer',
    department: 'Engineering',
    departmentId: 'dept1',
    managerId: 'e1',
    managerName: 'John Doe',
    employmentType: 'full-time',
    status: 'active',
    hireDate: '2020-06-15',
    salary: 165000,
    currency: 'USD',
    location: 'San Francisco, CA',
    workEmail: 'jane.smith@company.com',
    skills: ['React', 'TypeScript', 'Node.js', 'AWS'],
    bio: 'Full-stack engineer passionate about clean code.',
  },
  {
    id: 'e3',
    employeeId: 'EMP-004',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sjohnson@company.com',
    phone: '+1 (555) 200-0001',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    jobTitle: 'VP of Sales',
    department: 'Sales',
    departmentId: 'dept2',
    managerId: 'e0',
    managerName: 'Robert Anderson',
    employmentType: 'full-time',
    status: 'active',
    hireDate: '2019-05-10',
    salary: 200000,
    currency: 'USD',
    location: 'New York, NY',
    workEmail: 'sarah.johnson@company.com',
    skills: ['Sales Strategy', 'Negotiation', 'CRM', 'Team Building'],
    directReports: ['e4', 'e12'],
  },
  {
    id: 'e4',
    employeeId: 'EMP-005',
    firstName: 'Mike',
    lastName: 'Wilson',
    email: 'mwilson@company.com',
    phone: '+1 (555) 200-0002',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
    jobTitle: 'Account Executive',
    department: 'Sales',
    departmentId: 'dept2',
    managerId: 'e3',
    managerName: 'Sarah Johnson',
    employmentType: 'full-time',
    status: 'active',
    hireDate: '2021-02-01',
    salary: 95000,
    currency: 'USD',
    location: 'New York, NY',
    workEmail: 'mike.wilson@company.com',
    skills: ['Sales', 'Presentation', 'Customer Relations'],
  },
  {
    id: 'e5',
    employeeId: 'EMP-006',
    firstName: 'Emily',
    lastName: 'Chen',
    email: 'echen@company.com',
    phone: '+1 (555) 300-0001',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    jobTitle: 'Marketing Director',
    department: 'Marketing',
    departmentId: 'dept3',
    managerId: 'e0',
    managerName: 'Robert Anderson',
    employmentType: 'full-time',
    status: 'active',
    hireDate: '2020-01-15',
    salary: 150000,
    currency: 'USD',
    location: 'San Francisco, CA',
    workEmail: 'emily.chen@company.com',
    skills: ['Digital Marketing', 'Brand Strategy', 'Analytics', 'Content'],
    directReports: ['e6'],
  },
  {
    id: 'e6',
    employeeId: 'EMP-007',
    firstName: 'Alex',
    lastName: 'Rivera',
    email: 'arivera@company.com',
    phone: '+1 (555) 300-0002',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    jobTitle: 'Marketing Specialist',
    department: 'Marketing',
    departmentId: 'dept3',
    managerId: 'e5',
    managerName: 'Emily Chen',
    employmentType: 'full-time',
    status: 'on-leave',
    hireDate: '2022-03-01',
    salary: 75000,
    currency: 'USD',
    location: 'Remote',
    workEmail: 'alex.rivera@company.com',
    skills: ['Social Media', 'SEO', 'Copywriting'],
  },
  {
    id: 'e7',
    employeeId: 'EMP-008',
    firstName: 'Michael',
    lastName: 'Brown',
    email: 'mbrown@company.com',
    phone: '+1 (555) 400-0001',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    jobTitle: 'HR Director',
    department: 'Human Resources',
    departmentId: 'dept4',
    managerId: 'e0',
    managerName: 'Robert Anderson',
    employmentType: 'full-time',
    status: 'active',
    hireDate: '2019-08-20',
    salary: 140000,
    currency: 'USD',
    location: 'San Francisco, CA',
    workEmail: 'michael.brown@company.com',
    skills: ['HR Management', 'Recruiting', 'Employee Relations', 'Compliance'],
  },
  {
    id: 'e8',
    employeeId: 'EMP-009',
    firstName: 'Lisa',
    lastName: 'Wang',
    email: 'lwang@company.com',
    phone: '+1 (555) 500-0001',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
    jobTitle: 'CFO',
    department: 'Finance',
    departmentId: 'dept5',
    managerId: 'e0',
    managerName: 'Robert Anderson',
    employmentType: 'full-time',
    status: 'active',
    hireDate: '2018-06-01',
    salary: 250000,
    currency: 'USD',
    location: 'San Francisco, CA',
    workEmail: 'lisa.wang@company.com',
    skills: ['Financial Planning', 'Accounting', 'Risk Management', 'M&A'],
  },
  {
    id: 'e9',
    employeeId: 'EMP-010',
    firstName: 'David',
    lastName: 'Miller',
    email: 'dmiller@company.com',
    phone: '+1 (555) 600-0001',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    jobTitle: 'Operations Director',
    department: 'Operations',
    departmentId: 'dept6',
    managerId: 'e0',
    managerName: 'Robert Anderson',
    employmentType: 'full-time',
    status: 'active',
    hireDate: '2020-02-10',
    salary: 145000,
    currency: 'USD',
    location: 'Austin, TX',
    workEmail: 'david.miller@company.com',
    skills: ['Operations Management', 'Process Optimization', 'Logistics'],
  },
  {
    id: 'e10',
    employeeId: 'EMP-011',
    firstName: 'Kevin',
    lastName: 'Park',
    email: 'kpark@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kevin',
    jobTitle: 'Software Engineer',
    department: 'Engineering',
    departmentId: 'dept1',
    managerId: 'e1',
    managerName: 'John Doe',
    employmentType: 'full-time',
    status: 'active',
    hireDate: '2023-01-15',
    salary: 130000,
    currency: 'USD',
    location: 'San Francisco, CA',
    workEmail: 'kevin.park@company.com',
    skills: ['Python', 'Django', 'PostgreSQL'],
  },
  {
    id: 'e11',
    employeeId: 'EMP-012',
    firstName: 'Rachel',
    lastName: 'Green',
    email: 'rgreen@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rachel',
    jobTitle: 'QA Engineer',
    department: 'Engineering',
    departmentId: 'dept1',
    managerId: 'e1',
    managerName: 'John Doe',
    employmentType: 'contract',
    status: 'active',
    hireDate: '2023-06-01',
    salary: 110000,
    currency: 'USD',
    location: 'Remote',
    workEmail: 'rachel.green@company.com',
    skills: ['Testing', 'Automation', 'Selenium', 'Cypress'],
  },
  {
    id: 'e12',
    employeeId: 'EMP-013',
    firstName: 'Tom',
    lastName: 'Harris',
    email: 'tharris@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tom',
    jobTitle: 'Sales Representative',
    department: 'Sales',
    departmentId: 'dept2',
    managerId: 'e3',
    managerName: 'Sarah Johnson',
    employmentType: 'full-time',
    status: 'active',
    hireDate: '2023-09-01',
    salary: 70000,
    currency: 'USD',
    location: 'New York, NY',
    workEmail: 'tom.harris@company.com',
    skills: ['Cold Calling', 'Lead Generation', 'CRM'],
  },
]

export const mockOrgChart: OrgNode = {
  id: 'e0',
  name: 'Robert Anderson',
  title: 'CEO',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Robert',
  department: 'Executive',
  children: [
    {
      id: 'e1',
      name: 'John Doe',
      title: 'VP of Engineering',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
      department: 'Engineering',
      children: [
        { id: 'e2', name: 'Jane Smith', title: 'Senior Software Engineer', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane', department: 'Engineering' },
        { id: 'e10', name: 'Kevin Park', title: 'Software Engineer', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kevin', department: 'Engineering' },
        { id: 'e11', name: 'Rachel Green', title: 'QA Engineer', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rachel', department: 'Engineering' },
      ],
    },
    {
      id: 'e3',
      name: 'Sarah Johnson',
      title: 'VP of Sales',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
      department: 'Sales',
      children: [
        { id: 'e4', name: 'Mike Wilson', title: 'Account Executive', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike', department: 'Sales' },
        { id: 'e12', name: 'Tom Harris', title: 'Sales Representative', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tom', department: 'Sales' },
      ],
    },
    {
      id: 'e5',
      name: 'Emily Chen',
      title: 'Marketing Director',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
      department: 'Marketing',
      children: [
        { id: 'e6', name: 'Alex Rivera', title: 'Marketing Specialist', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex', department: 'Marketing' },
      ],
    },
    {
      id: 'e7',
      name: 'Michael Brown',
      title: 'HR Director',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
      department: 'Human Resources',
    },
    {
      id: 'e8',
      name: 'Lisa Wang',
      title: 'CFO',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
      department: 'Finance',
    },
    {
      id: 'e9',
      name: 'David Miller',
      title: 'Operations Director',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
      department: 'Operations',
    },
  ],
}

export const mockEmployeeStats: EmployeeStats = {
  total: 75,
  active: 72,
  onLeave: 3,
  newHires: 8,
  departments: 6,
  avgTenure: 2.5,
}
